import { Inter } from "next/font/google";
import { Metadata } from "next";
import GlobalStyle from "./global-style";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Do Study",
  description: "Generated by create next app",
  icons: "/ds.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <GlobalStyle />
    </html>
  );
}
