import { Metadata } from "next";
import GlobalStyle from "./global-style";
import Header from "@/app/_components/common/header";

export const metadata: Metadata = {
  title: "Do Study",
  description: "Generated by create next app",
  icons: "/ds.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <GlobalStyle />
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
