import { Metadata } from "next";
import GlobalStyle from "./global-style";
import RecoilRootWrapper from "./recoil-root-wrapper";
import ToastProvider from "./toast-provider";
import QueryProvider from "./query-provider";

export const metadata: Metadata = {
  title: "Do Study",
  description: "Generated by create next app",
  icons: "/ds.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <RecoilRootWrapper>
        <GlobalStyle />
        <body>
          <QueryProvider>
            <ToastProvider>{children}</ToastProvider>
          </QueryProvider>
        </body>
      </RecoilRootWrapper>
    </html>
  );
}
